---
version: 2
jobs:
  build:
    working_directory: ~/pile-jockey
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Make sure there is a JS runtime available
      - run: sudo apt-get update && sudo apt-get install nodejs

        - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: pile-jockey-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: pile-jockey-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Setup the database
      - run: bundle exec rails db:setup

      # Run the tests
      - run: bundle exec rspec
